### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by proxene** [davismiculis/G2APay#1]
Hello, 
I have a problem with the script that tells me:

`Fatal error: Uncaught Error: Call to a member function addItem () on null in /var/www/vhosts/***/index.php:22 Stack trace: # 0 {main } thrown in /var/www/vhosts/***/index.php on line 22`

And here is the build script (I have hidden my G2A Pay API)

```
<?php

require_once 'test.php';

use G2APay\G2APay;

// Set required variables
$hash = '*'; // Get it from G2APay
$secret = '*'; // Get it from G2APay
$success = 'http://example.com/success/'; // URL for successful callback;
$fail = 'http://example.com/failed/'; // URL for failed callback;
$order = 2234; // Choose your order id or invoice number, can be anything

// Optional
$extra = '';
$type = '';

// Optional
$currency = 'EUR'; // Pass currency, if no given will use "USD"

// Create payment instance
$payment->addItem(114, 'Game', 1, 114, 0.01, 'http://example.com/i/game/', $extra, $type);
    
// Create payment against G2APay
//$response = $payment->create();

// Or if you want to create sandbox payment (for testing only)
$response = $payment->test()->create();

// Check if successful
if ($response['success']) {
    header('Location: '.$response['url']); // redirect
} else {
    echo $response['message']; // print out error message
}

?>
```

Can you help me ?

Best regards,
Proxene

**Comment by davismiculis** [comment]
It appears you haven't created payment instance. `$payment = ...`

Check readme - https://github.com/davismiculis/G2APay#initialization

**Comment by proxene** [comment]
Hi :), 

I created payment instance et I have this error : Fatal error: Uncaught Error: Call to undefined method G2APay\G2APay::create() 

Can you help me ?

Best regards,
Proxene

**Comment by davismiculis** [comment]
Seems like I've written example incorrectly, method is called `createOrder`
