### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Galliger** [davismiculis/G2APay#2]
I set it all up and I am getting an error?

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function G2APay\G2APay::createOrder(), 0 passed in D:\Servers\WebServer\htdocs\index.php on line 42 and at least 1 expected in D:\Servers\WebServer\htdocs\G2APay.php:74 Stack trace: #0 D:\Servers\WebServer\htdocs\index.php(42): G2APay\G2APay->createOrder() #1 {main} thrown in D:\Servers\WebServer\htdocs\G2APay.php on line 74`

**Comment by Galliger** [comment]
```
<?php
require_once 'vendor/autoload.php'
?>

<?php
use G2APay\G2APay;

// Set required variables
$hash = 'HIDDEN'; // Get it from G2APay
$secret = 'HIDDEN'; // Get it from G2APay
$success = 'HIDDEN'; // URL for successful callback;
$fail = 'HIDDEN'; // URL for failed callback;
$order = 2234; // Choose your order id or invoice number, can be anything

// Optional
$currency = 'USD'; // Pass currency, if no given will use "USD"

// Create payment instance
$payment = new G2APay($hash, $secret, $success, $fail, $order, $currency);

// Set item parameters
$sku = 1; // Item number (In most cases $sku can be same as $id)
$name = 'HIDDEN';
$quantity = 1; // Must be integer
$id = 1; // Your items' identifier
$price = 22.55; // Must be float
$url = 'HIDDEN';

// Optional
$extra = '';
$type = '';

// Add item to payment
$payment->addItem($sku, $name, $quantity, $id, $price, $url, $extra, $type);

// Create payment against G2APay
$response = $payment->createOrder();

// Or if you want to create sandbox payment (for testing only)
$response = $payment->test()->createOrder();
?>
```

**Comment by Galliger** [comment]
I get this error below when I install it using composer:
Fatal error: Uncaught Error: Call to undefined method G2APay\G2APay::createOrder() in D:\Servers\WebServer\htdocs\index.php:37 Stack trace: #0 {main} thrown in D:\Servers\WebServer\htdocs\index.php on line 37

**Comment by davismiculis** [comment]
Please pass required parameters to `createOrder()`

`createOrder($orderId, array $extra = [])`
