### ISSUE TITLE
G2A Pay - Always invalid store?

### ISSUE THREAD

**Issue by Galliger** [davismiculis/G2APay#3]
Hello.

I have set this up and I keep getting the response "Invalid store"

My API keys are completely fine and the store is setup and verified (I know this because it's working on a CMS)

But instead of using a CMS I want to make my own, but it keeps saying invalid store?

Have I done something wrong?

**Comment by Galliger** [comment]
It should be giving me a token just like it's doing on the CMS, but for some reason it will not.

And I just get the Json response of "Invalid Store", so there must be something wrong with the code as it's working file on my other website?

**Comment by davismiculis** [comment]
You should use test functionality for developing - `->test()->`, please read the README file!

Production environments has to be approved by G2A Pay to work.

**Comment by dmytro1** [comment]
Hy, Davis.
I got the same response "Invalid store" and use:
$response = $payment->test()->createOrder($orderId, $extras).
I test it from local environment (mamp + wp).
What it could be ? Tnx

**Comment by davismiculis** [comment]
Well, I think you should refer to G2A Pay documentation, also check if you're sending the correct data.

**Comment by dknu** [comment]
I get the same error.
Data such as hash and secret are correct.
I use the following code:

`$order = 2234; // Choose your order id or invoice number, can be anything

// Optional
$currency = 'USD'; // Pass currency, if no given will use "USD"

// Create payment instance
$payment = new G2APay($hash, $secret, $email, $success, $fail, $order, $currency);

// Set item parameters
$sku = 1; // Item number (In most cases $sku can be same as $id)
$name = 'testName';
$quantity = 1; // Must be integer
$id = 1; // Your items' identifier
$price = 9.95; // Must be float
$url = 'http://siteDomain.com/g2apay';

// Optional
$extra = '';
$type = '';

// Add item to payment
$payment->addItem($sku, $name, $quantity, $id, $price, $url, $extra, $type);

$orderId = 10193; // Generate or save in your database
$extras = []; // Optional extras passed to order (Please refer G2APay docs)
// Create payment against G2APay
$response = $payment->createOrder($extras);

// Or if you want to create sandbox payment (for testing only)
$response = $payment->test()->createOrder($orderId, $extras);

var_dump($response);`
Also to mention @davismiculis, the issue I created earlier about createOrder(), the function does not exist in the composer installation file. You should update it.

**Comment by dknu** [comment]
Invalid store for me as well, when using test(). Store is approved in g2a dashboard. Maybe it has to do with the product/item parameters in the example code you provided davis?

**Comment by davismiculis** [comment]
I will try to check whats going on as soon as I can, maybe something changed in G2A Pay, because I'm confident it used to work correctly.

**Comment by Demitor** [comment]
I don't know if you are using the production keys for the sandbox environment, but if you are you will get the 'Invalid store' error. You would the need to register at:  https://id.test.pay.g2a.com/ and email the merchant support.

More info about that can be found here: https://supporthub.g2a.com/pay/en/integration/Do-you-offer-a-sandbox-environment-for-testing

**Comment by davismiculis** [comment]
Yes, the sandbox and production has two entirey different accounts, if I remember correctly.
