### ISSUE TITLE
IPN System [Question]

### ISSUE THREAD

**Issue by proxene** [davismiculis/G2APay#4]
Hello,

I have a question, I saw that there was the function:

> 	public function checkTransaction(string $transactionCode = '')
	{
		// Temporary save rest api url, then reset to default
		$url = $this->restApiUrl;
		$this->restApiUrl = self::REST_API_URL;
		$headers = [
			'Authorization: '. $this->apiHash.';'.$this->calculateAuthHash(),
		];
		// Request API server
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url.'/rest/transactions/'.$transactionCode);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		// curl_setopt($ch, CURLOPT_POST, true);
		// curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query([]));
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		$response = curl_exec($ch);
		curl_close($ch);
		// Convert response from JSON text to PHP object/array
		$result = json_decode($response);
		return $result;
	}

Someone have an idea how we can rework this function to verify that the payment has been made successfully ?

Thank you in advance.

Best Regards,
Proxene

**Comment by davismiculis** [comment]
Check G2APay docs and see what the possible response is.
